# Fly.io configuration for German Letter AI Backend
# Run: flyctl deploy

app = "miniapp-wvsxfa"
primary_region = "fra"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[env]
  PORT = "8001"
  SQLITE_DB_PATH = "/app/data/german_ai.db"
  TESSERACT_AVAILABLE = "true"
  TESSERACT_VERSION = "5.3.0"
  PATH = "/usr/bin:/usr/local/bin:$PATH"

[[http_service.http_checks]]
  interval = "10s"
  grace_period = "10s"  
  method = "get"
  path = "/health"
  protocol = "http"
  timeout = "5s"
  tls_skip_verify = false

[[mounts]]
  source = "german_ai_data"
  destination = "/app/data"