# Fly.io configuration for German Letter AI Backend
# Run: flyctl deploy

app = "miniapp-wvsxfa"
primary_region = "fra"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[env]
  SQLITE_DB_PATH = "/tmp/german_ai.db"
  TESSERACT_AVAILABLE = "true"
  TESSERACT_VERSION = "5.3.0"
  PATH = "/usr/bin:/usr/local/bin:$PATH"

[processes]
  app = "uvicorn server:app --host 0.0.0.0 --port 8001"

[[services]]
  protocol = "tcp"
  internal_port = 8001
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[services.http_checks]]
  interval = "10s"
  grace_period = "5s"
  method = "get"
  path = "/health"
  protocol = "http"
  timeout = "2s"
  tls_skip_verify = false

[[services.tcp_checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "1s"